#!/usr/bin/env bash
# Display of listening UDP ports with PID/Program
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
netstat -tulpen
