#!/usr/bin/env bash
# Vérifie si un argument est passé en ligne de commande
if [ $# -eq 0 ]; then
    echo "Utilisation : $0 {IP_ADDRESS}"
    exit 1
fi

if [[ ! $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Adresse IP invalide."
    exit 1
fi

ip_address="$1"

ping_count=5

echo "Ping de l'adresse IP : $ip_address"
ping -c $ping_count $ip_address
