#!/usr/bin/env bash
# Add or modify the entry for localhost
sed -i '/127.0.0.1\s\+localhost/d' /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com www.facebook.com" >> /etc/hosts
cat /etc/hosts
